### ISSUE TITLE
$PAGE->url reference in settings.php throws notice

### ISSUE THREAD

**Issue by thepurpleblob** [streamingltd/MEDIAL-Moodle-Activity#5] opened 2019-02-28 15:31 UTC
This bit of code in settings.php

```
if ($PAGE->url->get_param("section")=="modsettinghelixmedia") {
    require_once($CFG->dirroot.'/mod/helixmedia/locallib.php');
    $settings->add(new admin_setting_heading('helixmedia/version_check', get_string("version_check_title", "mod_helixmedia"),
        helixmedia_version_check()));
}
```

throws the following notice with Developer debugging enabled...

> This page did not call $PAGE->set_url(...). Using http://pc164-239.cent.gla.ac.uk/moodle37/admin/search.php

It appears that the expected url has not been set prior to settings.php being called.

**Comment by thepurpleblob** [comment] 2019-03-26 11:09
Further... I can't see any reason to have a version check on this page at all. Moodle already has a facility to show new versions of plugins.

**Comment by tim1mw** [comment] 2019-06-18 08:34
Sorry for the slow reply, our normal bug report process doesn't use github so this isn't monitored.

@thepurpleblob the version check is testing the version of Medial you have is compatible with the plugin version that you have installed, it isn't checking for upgrades to the Moodle plugin itself, this still happens as part of the normal Moodle plugin update code.

Re the notice, the issue is that in some contexts Moodle is setting the page URL prior to calling this code, in others it doesn't hence the error. It's not the page URL I'm after here, I just want to suppress the version check (which involves an API call to MEDIAL so is quite slow) from being performed unless you're actually on the MEDIAL settings page, so I'll re-write this to use $PAGE->pagetype which is automatically set so should always be present and will tell me what I need to know. That will be in the next plugin release when it goes through QA, the code change will look like this if you want to manually patch your version in the interim:

if ($PAGE->pagetype=="admin-setting-modsettinghelixmedia") {
    require_once($CFG->dirroot.'/mod/helixmedia/locallib.php');
    $settings->add(new admin_setting_heading('helixmedia/version_check', get_string("version_check_title", "mod_helixmedia"),
        helixmedia_version_check()));
}

I'll trim out the superfluous global $CFG at the same time, as you say that's not actually needed.

**Comment by troywilliams** [comment] 2019-08-15 02:53
Hi,

I am getting the same notice.

```PHP
This page did not call $PAGE->set_url(...). Using https://gumbygold.box/learning_v3.7/admin/plugins.php
line 600 of /lib/pagelib.php: call to debugging()
line 820 of /lib/pagelib.php: call to moodle_page->magic_get_url()
line 64 of /mod/helixmedia/settings.php: call to moodle_page->__get()
line 89 of /lib/classes/plugininfo/mod.php: call to include()
line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
line 8363 of /lib/adminlib.php: call to require()
line 8250 of /lib/adminlib.php: call to admin_get_root()
line 203 of /admin/plugins.php: call to admin_externalpage_setup()
```

Using version 2019052102

Cheers

**Closed** 2019-08-15 15:07 UTC
